# receive data from the serial port and send to MQTT 
FROM fedora:latest
RUN dnf upgrade -y

COPY  ./raincounter /bin/rainbase
COPY ./rainbase.yml /etc/rainbase/rainbase.yml

ENTRYPOINT [ \
    "/bin/rainbase", \
    "rainbase", \
    "--config", \
    "/etc/rainbase/rainbase.yml" \
    ]


