services:

    mosquitto:
        image: eclipse-mosquitto:latest
        network_mode: "host"
        volumes:
            - "/home/raincloud/raincloud/docker/certs/server/:/mosquitto/config/ssl/"
            - "/home/raincloud/raincloud/docker/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf"
